<?php
/**
 * Plugin Name:       Acme Notes
 * Plugin URI:        https://github.com/mlbd/kuira-wp-dev-plugin
 * Description:        Reference plugin generated by /wp-new (React + settings + secure REST + custom table). Demonstrates the kuira toolkit's output.
 * Version:           0.1.0
 * Requires at least: 6.0
 * Requires PHP:      7.4
 * Author:            Kuira
 * Author URI:        https://github.com/mlbd
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       acme-notes
 * Domain Path:       /languages
 *
 * @package Acme_Notes
 */

// Abort if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'ACME_NOTES_VERSION', '0.1.0' );
define( 'ACME_NOTES_DB_VERSION', '1.0.0' );
define( 'ACME_NOTES_FILE', __FILE__ );
define( 'ACME_NOTES_DIR', plugin_dir_path( __FILE__ ) );
define( 'ACME_NOTES_URL', plugin_dir_url( __FILE__ ) );

require_once ACME_NOTES_DIR . 'includes/class-acme-notes.php';

register_activation_hook( __FILE__, array( 'Acme_Notes_Activator', 'activate' ) );
register_deactivation_hook( __FILE__, array( 'Acme_Notes_Deactivator', 'deactivate' ) );

/**
 * Boot the plugin.
 *
 * @return Acme_Notes
 */
function acme_notes_run() {
	return Acme_Notes::get_instance();
}
add_action( 'plugins_loaded', 'acme_notes_run' );
